### ISSUE TITLE
i alredy build the app but the app keeps crashing after runing from AS

### ISSUE THREAD

**Issue by tronbiniyam** [DineshNeupane/nCOVIDroid#5]
this is the log i got from my phone 
E/AsyncHttpRH: User-space exception detected!
    java.lang.NumberFormatException: For input string: "2020-03-26 23:48:35"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.parseInt(Integer.java:643)
        at com.dineshneupane.ncovidroid.ui.home.HomeFragment$2.onSuccess(HomeFragment.java:139)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:354)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:513)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by DineshNeupane** [comment]
This is happening because the data source has changed the format of data in which it is provided. Can you please fork the project and correct the issues that would be great. the data source is here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports
